/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as FavoritesImport } from './routes/favorites';
import { Route as IndexImport } from './routes/index';
import { Route as CharactersCharacterIdImport } from './routes/characters.$characterId';

// Create/Update Routes

const FavoritesRoute = FavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const CharactersCharacterIdRoute = CharactersCharacterIdImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/favorites': {
      id: '/favorites';
      path: '/favorites';
      fullPath: '/favorites';
      preLoaderRoute: typeof FavoritesImport;
      parentRoute: typeof rootRoute;
    };
    '/characters/$characterId': {
      id: '/characters/$characterId';
      path: '/characters/$characterId';
      fullPath: '/characters/$characterId';
      preLoaderRoute: typeof CharactersCharacterIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/favorites': typeof FavoritesRoute;
  '/characters/$characterId': typeof CharactersCharacterIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/favorites': typeof FavoritesRoute;
  '/characters/$characterId': typeof CharactersCharacterIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/favorites': typeof FavoritesRoute;
  '/characters/$characterId': typeof CharactersCharacterIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/favorites' | '/characters/$characterId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/favorites' | '/characters/$characterId';
  id: '__root__' | '/' | '/favorites' | '/characters/$characterId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FavoritesRoute: typeof FavoritesRoute;
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorites",
        "/characters/$characterId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favorites": {
      "filePath": "favorites.tsx"
    },
    "/characters/$characterId": {
      "filePath": "characters.$characterId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
